/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutViewCompEn: typeof import('./src/components/views/AboutViewCompEn.vue')['default']
    AboutViewCompZhCn: typeof import('./src/components/views/AboutViewCompZhCn.vue')['default']
    AboutViewCompZhTw: typeof import('./src/components/views/AboutViewCompZhTw.vue')['default']
    CharacterSearch: typeof import('./src/components/search/CharacterSearch.vue')['default']
    CharacterSearchEntry: typeof import('./src/components/search/CharacterSearchEntry.vue')['default']
    CharacterSheet: typeof import('./src/components/CharacterSheet.vue')['default']
    CharVoiceNexonBattle: typeof import('./src/components/voice/CharVoiceNexonBattle.vue')['default']
    CharVoiceNexonEvent: typeof import('./src/components/voice/CharVoiceNexonEvent.vue')['default']
    CharVoiceNexonNormal: typeof import('./src/components/voice/CharVoiceNexonNormal.vue')['default']
    CharVoiceNexonUi: typeof import('./src/components/voice/CharVoiceNexonUi.vue')['default']
    CharVoiceSchaleDbContent: typeof import('./src/components/voice/CharVoiceSchaleDbContent.vue')['default']
    CharVoiceSchaleDbUi: typeof import('./src/components/voice/CharVoiceSchaleDbUi.vue')['default']
    CharVoiceUi: typeof import('./src/components/voice/CharVoiceUi.vue')['default']
    DataVersionDisplay: typeof import('./src/components/DataVersionDisplay.vue')['default']
    DialogueDesktopAuto: typeof import('./src/components/scenario/desktop/DialogueDesktopAuto.vue')['default']
    DialogueDesktopNormal: typeof import('./src/components/scenario/desktop/DialogueDesktopNormal.vue')['default']
    DialogueDesktopOption: typeof import('./src/components/scenario/desktop/DialogueDesktopOption.vue')['default']
    DialogueDesktopOther: typeof import('./src/components/scenario/desktop/DialogueDesktopOther.vue')['default']
    DialogueIcon: typeof import('./src/components/DialogueIcon.vue')['default']
    DialogueInfo: typeof import('./src/components/scenario/DialogueInfo.vue')['default']
    DialogueMobileAuto: typeof import('./src/components/scenario/mobile/DialogueMobileAuto.vue')['default']
    DialogueMobileNormal: typeof import('./src/components/scenario/mobile/DialogueMobileNormal.vue')['default']
    DialogueMobileOption: typeof import('./src/components/scenario/mobile/DialogueMobileOption.vue')['default']
    DialogueMobileOther: typeof import('./src/components/scenario/mobile/DialogueMobileOther.vue')['default']
    DialogueTranslated: typeof import('./src/components/DialogueTranslated.vue')['default']
    MessageStudent: typeof import('./src/components/momotalk/MessageStudent.vue')['default']
    MessageStudentMobile: typeof import('./src/components/momotalk/MessageStudentMobile.vue')['default']
    MomotalkHeader: typeof import('./src/components/momotalk/MomotalkHeader.vue')['default']
    MomotalkMessageAuto: typeof import('./src/components/momotalk/MomotalkMessageAuto.vue')['default']
    MomotalkUi: typeof import('./src/components/MomotalkUi.vue')['default']
    NexonI18nDataOutput: typeof import('./src/components/genetic/NexonI18nDataOutput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenarioDialogue: typeof import('./src/components/scenario/ScenarioDialogue.vue')['default']
    ScenarioIsAfterBattleBadge: typeof import('./src/components/genetic/ScenarioIsAfterBattleBadge.vue')['default']
    ScenarioRelatedStory: typeof import('./src/components/scenario/ScenarioRelatedStory.vue')['default']
    ScenarioSearch: typeof import('./src/components/search/ScenarioSearch.vue')['default']
    ScenarioSearchChapterMetadata: typeof import('./src/components/search/ScenarioSearchChapterMetadata.vue')['default']
    ScenarioSearchEntryBond: typeof import('./src/components/search/ScenarioSearchEntryBond.vue')['default']
    ScenarioSearchEntryEvent: typeof import('./src/components/search/ScenarioSearchEntryEvent.vue')['default']
    ScenarioSheet: typeof import('./src/components/scenario/ScenarioSheet.vue')['default']
    ScenarioUi: typeof import('./src/components/ScenarioUi.vue')['default']
    SettingDialog: typeof import('./src/components/setting/SettingDialog.vue')['default']
    StoryI18nSetting: typeof import('./src/components/setting/StoryI18nSetting.vue')['default']
  }
}
