/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DialogueAuto: typeof import('./src/components/scenario/desktop/DialogueAuto.vue')['default']
    DialogueAutoMobile: typeof import('./src/components/scenario/mobile/DialogueAutoMobile.vue')['default']
    DialogueInfo: typeof import('./src/components/scenario/DialogueInfo.vue')['default']
    DialogueNormal: typeof import('./src/components/scenario/desktop/DialogueNormal.vue')['default']
    DialogueOption: typeof import('./src/components/scenario/desktop/DialogueOption.vue')['default']
    DialogueOther: typeof import('./src/components/scenario/desktop/DialogueOther.vue')['default']
    DialogueStudent: typeof import('./src/components/momotalk/DialogueStudent.vue')['default']
    DialogueStudentMobile: typeof import('./src/components/momotalk/DialogueStudentMobile.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    MomotalkDialogue: typeof import('./src/components/momotalk/MomotalkDialogue.vue')['default']
    MomotalkHeader: typeof import('./src/components/momotalk/MomotalkHeader.vue')['default']
    MomotalkSearch: typeof import('./src/components/search/MomotalkSearch.vue')['default']
    MomotalkSearchEntry: typeof import('./src/components/search/MomotalkSearchEntry.vue')['default']
    MomotalkUi: typeof import('./src/components/MomotalkUi.vue')['default']
    NexonI18nDataOutput: typeof import('./src/components/genetic/NexonI18nDataOutput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenarioDatasheet: typeof import('./src/components/ScenarioDatasheet.vue')['default']
    ScenarioDialogue: typeof import('./src/components/scenario/ScenarioDialogue.vue')['default']
    ScenarioIsAfterBattleBadge: typeof import('./src/components/genetic/ScenarioIsAfterBattleBadge.vue')['default']
    ScenarioSearch: typeof import('./src/components/search/ScenarioSearch.vue')['default']
    ScenarioSearchEntryBond: typeof import('./src/components/search/ScenarioSearchEntryBond.vue')['default']
    ScenarioSearchEntryEvent: typeof import('./src/components/search/ScenarioSearchEntryEvent.vue')['default']
    ScenarioUi: typeof import('./src/components/ScenarioUi.vue')['default']
    StoryI18nSetting: typeof import('./src/components/setting/StoryI18nSetting.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
