<script setup lang="ts">
import PvMessage from 'primevue/message'
import CharacterSheet from '@/components/CharacterSheet.vue'
</script>

<template>
  <h1 class="view-h1">Misakiii!</h1>
  <PvMessage severity="error">
    <span>Unless specified, we're talking about <RouterLink to="/character/10041">this Misaki</RouterLink>, not <RouterLink to="/character/10080">that Misaki</RouterLink>.</span>
  </PvMessage>
  <br />
  <CharacterSheet :is-mmt="false" char-id="10041" />
  <p>Oh wow, wasn't really expecting that you'd be actually curious enough to click on that link. Now that you're here, maybe you can take a rest and hear me rambling for a while before continuing your journey? Of course, you can go back ay any time if you want.</p>
  <br />
  <p style="font-size: 1.1em"><i>To my beloved girl, <b>Imashino Misaki</b> of the Arius Squad. You always have my back.</i></p>
  <p>The first time I encountered Misaki, as far as I can tell, will lead us back to the conflicts of the Eden Treaty, when the whole squad was introduced for the first time as well. Being "depressed" and "low-spirited" would be my first impression on her, but that's not saying I was well prepared for her attempted suicide on that bridge later in the story.</p>
  <p>Much to my regret however, I didn't really see the her unique charm as a character, and wasn't really able to recognize the internal <i>connections</i> in terms of personal stories (albeit for very different reasons.) After all, Blue Archive isn't a game where dark, cruel stories are served as the main dishes (and even that's actually the case, it'd certainly be a good ending for each student), and in a world where exceptionally charming characters like Yuuka, Hina, Mika, etc. exist, it even make it harder for people to choose characters much less popular, not to mention a groomy one like Misaki.</p>
  <p>That is, until I pulled her out by pure chance, and I started to get Momotalks cleared.</p>
  <p>Now, when it comes to character evaluation, I don't really care much about the character (portrait) design, but rather their stories and writings. By that means, and no offense intended here, the FOX Platoon, for instance, are exactly the ones I don't really that like, simply due to their involvements in Vol. 4 Chap. 2, despite their appealing designs. Misaki goes in the same way, in which it is the stories that really strikes my heart deeply.</p>
  <p>Misaki is, at its roots, s girl who hold Nihilism as the ultimate answer and her only belief, a thing that we aren't unfamiliar with other Arius students (notably, Azusa as well.) But, just like what Redditor <a target="_blank" href="https://www.reddit.com/user/Genprey/">u/Genprey</a> pointed out in his/her "Student Profile" series posts, Misaki is the most critical one among the Squad and is urgently requiring intervention. As depicted in the main story, Misaki attempted not only once (on that bridge witnessed by Sensei,) but multiple times kn her childhood, and not even Saori can very much completely stop her from doing that. This alone would be enough to trigger our sympathy feeling, but to say, be an actual <i>Misaki bro</i> or <i>Misaki fan</i>, would require us to five further into his third bond story, where my personal connection with her is finally established.</p>
  <p>At a rainy right on a street of downtown D.U., Sensei saw a soaked Misaki with rather high fever. Misaki admitted that she hadn't eaten or slept for days, and then she collapsed to the ground before even finishing her words. Like every <i>responsible</i> adult would do, Sensei got her out of the street and rented a clean room at a nearby hotel, telling here to get clothes changed and have a good rest, before leaving for some medicine.</p>
  <p>In the room, alone with herself again, Misaki cursed on the world, complained about her physical body being nothing but "a meaningless vessel that always got into her ways," and expressed her wish to <i>vanish</i>. All of this are completely understandable, but what comes right after, as noted by u/Genprey as "the most significant character progression", touched my heart deeply.</p>
  <p>Misaki said, "I'm... so <i>lonely</i>." This would mark the first major mental state shift in her stories, as this implied that she had come to the realization that "Sensei isn't here with me anymore," indicating her dependence and affection towards Sensei. For the first time in the story, Misaki lowered her guards, now complaining Sensei's absence.</p>
  <p>When Sensei got back, Misaki was sitting besides the window, a fairly common move by any suicidal person. But unlike other suicidal person, this scene, at least to me personally, foils be interpreted as her trying to accept the brutality of the world and her own weakness, and probably also, expecting Sensei to come back. As per her memorial lobby lines, she was comforted and relieved, knowing that Sensei would be by her side for forever.</p>
  <p>Misaki's perception to the world, that the world is empty and any struggle is meaningless, is something that all of us might experience at least once in the lifetime. Academic pressure is an instance that can lead to cases very similar to Misaki's; as of writing this , I have experienced it two times and am currently experiencing the third time. It's a notoriously difficult experience, especially mental-wisez and the fact that the number of students choosing to end their lives becuase of this, is alarming and heart-breaking. As someone who has recovered from this before, it only makes sense for me to love her, to care her, to attend to her, with my utmost, for more beyond any other girls in the game.</p>
  <p>What shatters my heart more however, is that upon doing some research on Misaki, I come across her self introduction line, which reads "(now that) I'm like a hound that's been abandoned... (So) Here's my lead, and I'm at your disposal." To call herself a "hound" (dog, essentially,) and use the word "lead" (more commonly, the <i>leash</i> for a dog,) is something that absolutely blows my mind. I don't think that any other students, or anyone in the Arius Squad would refer themselves that way. I'm so shocked when I actually read through that for the first time. It's simply painfully unbearable.</p>
  <br />
  <p>Months later and it was 0068 Opera event, where the Valentine's Day story made a comeback. Following my curiosity and having been suggested by some of my friends, I chose Misaki's as my first story to read, and it did turn out to be comforting.</p>
  <p>Using "checking the unity lines" as a facade, Misaki gifted Sensei a chocolate she made in a blushed face. Although it's what writers are supposed to write in such settings, I still found it to be a great character progression, for that we now have a clear confirmation that she's actually remembering Sensei.</p>
  <p>When you have someone that you truly care about, it'd be hard for you to do things recklessly, because you don't want to make them down. In the case of Misaki, she's less suicidal because not only Sensei has helped her, but also she doesn't want Sensei to worry about her that much - and through this means, Misaki has found a meaning to live on, that is, to see Sensei.</p>
  <p>For other girls, especially the ones like Noa and Ichika, this increased level of attachment and intimacy could very likely develop into a state that many artworks have depicted, i.e. YANDERE. But that really isn't a problem for Misaki and perhaps the Arius Squad as a whole, and speaking for myself here, I'd be more than willing to give Misaki more hugs, teddy bears and so on. Just like Sensei's line in Vol. F, <i>No child should suffer from any pains</i>.</p>
  <br />
  <p>For the Arius Squad swimsuit event (coming to global soon), I haven't really gotten the time to read translated stories, so I'll just wait until it's available on Global. But it's said that Misaki finally smiles during the story, so I'm pretty looking forward to that. As a Misaki fan, it's rather a piru that Misaki (Swimsuit) wasn't added to the game last year, but given that it's been a fairly common practice by the devs to release characters gradually, I guess I'd have to wait for it.</p>
  <p>I'm also very grateful to be able to follow some artists and people on X/Twitter, who post stuff about Misaki/Arius Squad regularly. It's true that I don't have a very constant flow of new fanworks to see everyday, but this is already very impressive and very enough for an unpopular character, I suppose.</p>
  <br />
  <p>At last, thank you for your reading. It took me some time to actually get into Misaki, and even some more time to eventually become a Misaki fan. To quote a sentence, from u/Genprey's passage, "If you ask me whether Saori can succeed and grow in the future, my answer is yes." For Misaki I have the same faith for her, but that's going to be a long, long way.</p>
  <p>Btw, if you're curious about the other girls I like are Utaha (Cheerleader) and Azusa (both varients). Actually, I think Azusa and Misaki are two interesting characters when compared side-by-side, as they started out to be very much the same in their beliefs, but at the end they landed on the two extremes of Nihilism, something known as "positive/negative Nihilism" respectively. Azusa is the first character that I found myself personally connected, partly due to her unyielding spirit in making herself a better, optimistic person.</p>
  <p>Okay, now this article would be officially concluded. You may return to your work and again, thank you for reading a stranger's ramble on a character that you might not like.</p>
  <br />
  <p>2024/01/04 15:57 SAT.</p>
</template>

<style scoped>

</style>